name: Package-prod

on:
  push:
    branches: [ "master"]
     
  pull_request:
     branches: [ "master"]

jobs:
  Package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build with NPM and Create WAR file
        run: |
            npm config set legacy-peer-deps true
            npm install -g @angular/cli
            npm install -g grunt-cli
            npm install typescript@2.7.2 --save-dev
            npm install ng2-smart-table@1.2.1
            npm install node-sass --force
            npm install --force
            npm run ng build --prod --aot && grunt
        
      - name: Upload WAR file as artifact
        uses: actions/upload-artifact@v2 
        with:
          name: Admin-UI
          path: target/ 
